#include "utils.h"

/*
Find the n’th term in Look-and-say (Or Count and Say) Sequence.
 The look-and-say sequence is the sequence of the below integers:
1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, …

How is the above sequence generated?
n’th term is generated by reading (n-1)’th term.

The first term is "1"

Second term is "11", generated by reading first term as "One 1"
(There is one 1 in previous term)
Third term is "21", generated by reading second term as "Two 1"
Fourth term is "1211", generated by reading third term as "One 2 One 1"

and so on
*/

std::string CountAndSay(int n)
{
    if (n == 1) return "1";
    if (n == 2) return "11";

    int cnt = 1;
    std::string str = "11";
    for (int i = 3; i <=n; i++) {
        str += "$";  // ending marker  ?? NOTE here !!!!
        std::string cur;
        for (int j = 1; j < str.size(); j++) {
            if (str[j] == str[j-1]) {
                cnt++;
            } else {
                cur += (cnt + '0');
                cur += str[j-1];
                cnt = 1;
            }
        }
        std::cout << i << " : " << cur << "\n";
        str = cur;
    }
    return str;
}

int main()
{
    {
        int n = 10;
        std::cout << CountAndSay(n) << "\n";
    }
}
